service: simple-web-app
owner: dev-team
complianceFramework: commercial

components:
  # Simple web server
  - name: web-server
    type: ec2-instance
    config:
      instanceType: t3.micro
      ami:
        namePattern: 'al2023-ami-*-x86_64'
        owner: 'amazon'
      userData:
        script: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          echo "<h1>Hello from CDK Platform</h1>" > /var/www/html/index.html
      storage:
        rootVolumeSize: 20
        encrypted: true

  # Application storage
  - name: app-storage
    type: s3-bucket
    config:
      bucketName: simple-web-app-storage
      versioning: true
      encryption:
        enabled: true