$schema: platform-kb/pack@v1
pack:
  id: aws.global.logging
  version: "2025-09-01"
  description: "Logging operational best practices"
rules:
  - id: CFG_VPC_FLOW_LOGS
    title: "VPC Flow Logs enabled"
    severity: medium
    nist_controls: ["AU-2","AU-12"]
    services: ["vpc"]
    check:
      type: "aws-config-rule"
      name: "vpc-flow-logs-enabled"
  - id: CFG_S3_ACCESS_LOGGING_ENABLED
    title: "S3 access logging enabled"
    severity: medium
    nist_controls: ["AU-2","AU-12"]
    services: ["s3-bucket"]
    check:
      type: "aws-config-rule"
      name: "s3-bucket-logging-enabled"
