# Platform Configuration for FedRAMP Moderate Cloud Deployments  
# Version: 1.0
# Compliance Framework: FedRAMP Moderate

# API Gateway Configuration Defaults
api-gateway-rest:
  cors:
    allowOrigins:
      - "https://*.gov"
      - "https://*.mil" 
      - "https://admin.agency.gov"
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"] # No PATCH for compliance
    allowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    allowCredentials: false # Disabled for government security
    maxAge: 300 # Short cache for security
  throttling:
    burstLimit: 1000 # Conservative limits
    rateLimit: 500
  tracing:
    xrayEnabled: true # Mandatory for compliance

api-gateway-http:
  cors:
    allowOrigins:
      - "https://*.gov"
      - "https://*.mil"
      - "https://admin.agency.gov"
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowHeaders:
      - "Content-Type" 
      - "Authorization"
      - "X-Requested-With"
    allowCredentials: false
    maxAge: 300
  throttling:
    burstLimit: 1500
    rateLimit: 750
  accessLogging:
    enabled: true # Mandatory for compliance
    format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","responseLength":"$context.responseLength","userAgent":"$context.identity.userAgent"}'