# Platform Configuration for FedRAMP High Cloud Deployments
# Version: 1.0  
# Compliance Framework: FedRAMP High

defaults:
  # API Gateway Configuration Defaults
  api-gateway-rest:
    cors:
      allowOrigins: [] # NO cross-origin requests allowed by default - must be explicitly configured per service
      allowMethods: ["GET", "POST", "OPTIONS"] # Minimal methods only
      allowHeaders:
        - "Content-Type"
        - "Authorization"
      allowCredentials: false # Always disabled for highest security
      maxAge: 60 # Very short cache
    throttling:
      burstLimit: 200 # Very restrictive
      rateLimit: 100
    tracing:
      xrayEnabled: true # Mandatory for compliance

  api-gateway-http:
    cors:
      allowOrigins: [] # NO cross-origin requests allowed by default
      allowMethods: ["GET", "POST", "OPTIONS"] # Minimal methods only
      allowHeaders:
        - "Content-Type"
        - "Authorization"
      allowCredentials: false
      maxAge: 60
    throttling:
      burstLimit: 300 # Still very restrictive  
      rateLimit: 150
    accessLogging:
      enabled: true # Mandatory comprehensive logging
      format: '{"timestamp":"$context.requestTime","requestId":"$context.requestId","sourceIp":"$context.identity.sourceIp","method":"$context.httpMethod","path":"$context.routeKey","protocol":"$context.protocol","status":"$context.status","error":"$context.error.message","responseLength":"$context.responseLength","responseTime":"$context.responseLatency","userAgent":"$context.identity.userAgent","requestHeaders":"$context.requestHeaders"}'

  # WAF Web ACL Configuration Defaults
  waf-web-acl:
    scope: REGIONAL
    defaultAction: block # Most restrictive for FedRAMP High
    managedRuleGroups:
      - name: AWSManagedRulesCommonRuleSet
        vendorName: AWS
        priority: 1
        overrideAction: none
      - name: AWSManagedRulesKnownBadInputsRuleSet
        vendorName: AWS
        priority: 2
        overrideAction: none
      - name: AWSManagedRulesSQLiRuleSet
        vendorName: AWS
        priority: 3
        overrideAction: none
      - name: AWSManagedRulesLinuxRuleSet
        vendorName: AWS
        priority: 4
        overrideAction: none
      - name: AWSManagedRulesUnixRuleSet
        vendorName: AWS
        priority: 5
        overrideAction: none
    logging:
      enabled: true # Mandatory for compliance
      logDestinationType: cloudwatch
      redactedFields: []
    monitoring:
      enabled: true
      detailedMetrics: true # Mandatory for FedRAMP
      alarms:
        blockedRequestsThreshold: 100 # Stricter threshold
        allowedRequestsThreshold: 2000 # Stricter threshold
        sampledRequestsEnabled: true