# Platform Configuration for FedRAMP High Cloud Deployments
# Version: 1.0  
# Compliance Framework: FedRAMP High

defaults:
  # API Gateway Configuration Defaults
  api-gateway-rest:
    cors:
      allowOrigins: [] # NO cross-origin requests allowed by default - must be explicitly configured per service
      allowMethods: ["GET", "POST", "OPTIONS"] # Minimal methods only
      allowHeaders:
        - "Content-Type"
        - "Authorization"
      allowCredentials: false # Always disabled for highest security
      maxAge: 60 # Very short cache
    throttling:
      burstLimit: 200 # Very restrictive
      rateLimit: 100
    tracing:
      xrayEnabled: true # Mandatory for compliance

  api-gateway-http:
    cors:
      allowOrigins: [] # NO cross-origin requests allowed by default
      allowMethods: ["GET", "POST", "OPTIONS"] # Minimal methods only
      allowHeaders:
        - "Content-Type"
        - "Authorization"
      allowCredentials: false
      maxAge: 60
    throttling:
      burstLimit: 300 # Still very restrictive  
      rateLimit: 150
    accessLogging:
      enabled: true # Mandatory comprehensive logging
      format: '{"timestamp":"$context.requestTime","requestId":"$context.requestId","sourceIp":"$context.identity.sourceIp","method":"$context.httpMethod","path":"$context.routeKey","protocol":"$context.protocol","status":"$context.status","error":"$context.error.message","responseLength":"$context.responseLength","responseTime":"$context.responseLatency","userAgent":"$context.identity.userAgent","requestHeaders":"$context.requestHeaders"}'

  # WAF Web ACL Configuration Defaults
  waf-web-acl:
    scope: REGIONAL
    defaultAction: block # Most restrictive for FedRAMP High
    managedRuleGroups:
      - name: AWSManagedRulesCommonRuleSet
        vendorName: AWS
        priority: 1
        overrideAction: none
      - name: AWSManagedRulesKnownBadInputsRuleSet
        vendorName: AWS
        priority: 2
        overrideAction: none
      - name: AWSManagedRulesSQLiRuleSet
        vendorName: AWS
        priority: 3
        overrideAction: none
      - name: AWSManagedRulesLinuxRuleSet
        vendorName: AWS
        priority: 4
        overrideAction: none
      - name: AWSManagedRulesUnixRuleSet
        vendorName: AWS
        priority: 5
        overrideAction: none
    logging:
      enabled: true # Mandatory for compliance
      logDestinationType: cloudwatch
      redactedFields: []
    monitoring:
      enabled: true
      detailedMetrics: true # Mandatory for FedRAMP
      alarms:
      blockedRequestsThreshold: 100 # Stricter threshold
      allowedRequestsThreshold: 2000 # Stricter threshold
      sampledRequestsEnabled: true

  # VPC Configuration Defaults
  vpc:
    cidr: 10.0.0.0/16
    maxAzs: 3 # Multi-AZ required for high compliance
    natGateways: 2 # Redundancy required
    flowLogsEnabled: true
    flowLogRetentionDays: 2555 # 7 years for FedRAMP high
    subnets:
      public:
        cidrMask: 27 # Very small public subnets
        name: Public
      private:
        cidrMask: 25 # Larger private subnets
        name: Private
      database:
        cidrMask: 28
        name: Database
    vpcEndpoints:
      s3: true # All endpoints required
      dynamodb: true
      secretsManager: true
      kms: true
    dns:
      enableDnsHostnames: true
      enableDnsSupport: true
    monitoring:
      enabled: true
      detailedMetrics: true # Required for compliance
      alarms:
        natGatewayPacketDropThreshold: 250 # Most sensitive
        vpcFlowLogDeliveryFailures: 3

  # Step Functions State Machine Configuration
  step-functions-statemachine:
    stateMachineType: "STANDARD"
    loggingConfiguration:
      enabled: true # Mandatory for FedRAMP High
      level: "ALL"
      includeExecutionData: true # Required for detailed audit
    tracingConfiguration:
      enabled: true # Mandatory for high security
    timeout:
      seconds: 1800 # Shorter timeout for security (30 minutes)
    tags:
      service-type: "workflow"
      compliance-framework: "fedramp-high"
      logging-level: "comprehensive"
      audit-trail: "enabled"
      security-level: "high"