# Platform Configuration for FedRAMP Moderate Cloud Deployments  
# Version: 1.0
# Compliance Framework: FedRAMP Moderate

defaults:
  # API Gateway Configuration Defaults
  api-gateway-rest:
    cors:
      allowOrigins:
        - "https://*.gov"
        - "https://*.mil" 
        - "https://admin.agency.gov"
      allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"] # No PATCH for compliance
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "X-Requested-With"
      allowCredentials: false # Disabled for government security
      maxAge: 300 # Short cache for security
    throttling:
      burstLimit: 1000 # Conservative limits
      rateLimit: 500
    tracing:
      xrayEnabled: true # Mandatory for compliance

  api-gateway-http:
    cors:
      allowOrigins:
        - "https://*.gov"
        - "https://*.mil"
        - "https://admin.agency.gov"
      allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowHeaders:
        - "Content-Type" 
        - "Authorization"
        - "X-Requested-With"
      allowCredentials: false
      maxAge: 300
    throttling:
      burstLimit: 1500
      rateLimit: 750
    accessLogging:
      enabled: true # Mandatory for compliance
      format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":"$context.status","responseLength":"$context.responseLength","userAgent":"$context.identity.userAgent"}'

  # WAF Web ACL Configuration Defaults
  waf-web-acl:
    scope: REGIONAL
    defaultAction: block # More restrictive for FedRAMP
    managedRuleGroups:
      - name: AWSManagedRulesCommonRuleSet
        vendorName: AWS
        priority: 1
        overrideAction: none
      - name: AWSManagedRulesKnownBadInputsRuleSet
        vendorName: AWS
        priority: 2
        overrideAction: none
      - name: AWSManagedRulesSQLiRuleSet
        vendorName: AWS
        priority: 3
        overrideAction: none
      - name: AWSManagedRulesLinuxRuleSet
        vendorName: AWS
        priority: 4
        overrideAction: none
      - name: AWSManagedRulesUnixRuleSet
        vendorName: AWS
        priority: 5
        overrideAction: none
    logging:
      enabled: true # Mandatory for compliance
      logDestinationType: cloudwatch
      redactedFields: []
    monitoring:
      enabled: true
      detailedMetrics: true # Mandatory for FedRAMP
      alarms:
        blockedRequestsThreshold: 250
        allowedRequestsThreshold: 3000
        sampledRequestsEnabled: true